import type { TranscriptSegment } from "@/entity/Transcription";
import { formatDuration } from "@/app/components/utils";

export type ExportOpts = {
    title: string | null;
    summary: string | null;
    duration: number;
    createdAt: string | Date;
    segments: TranscriptSegment[];
};

const TITLE_FALLBACK = "Audia Transcript";
const SUMMARY_EMPTY_SENTINEL = "Not enough conversation to summarize.";

function toDate(createdAt: string | Date): Date {
    return createdAt instanceof Date ? createdAt : new Date(createdAt);
}

function formatHeaderDate(createdAt: string | Date): string {
    return toDate(createdAt).toLocaleString();
}

/**
 * Parses the AI summary string (which arrives as raw "• line\n• line"
 * bullets) into clean strings, dropping bullet glyphs and the
 * "not enough content" sentinel. Mirrors the parsing in SummaryBlock so
 * downloads match what the user sees on screen.
 */
function summaryBullets(summary: string | null): string[] {
    if (!summary) return [];
    if (summary.trim() === SUMMARY_EMPTY_SENTINEL) return [];
    return summary
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l.length > 0)
        .map((l) => l.replace(/^([•\-*]|\d+[.)]) */, "").trim())
        .filter((l) => l.length > 0);
}

export function formatTranscriptAsTxt(opts: ExportOpts): string {
    const lines: string[] = [];
    lines.push(opts.title ?? TITLE_FALLBACK);
    lines.push(`Recorded ${formatHeaderDate(opts.createdAt)} — ${formatDuration(opts.duration)}`);
    lines.push("");

    const bullets = summaryBullets(opts.summary);
    if (bullets.length > 0) {
        lines.push("SUMMARY");
        lines.push("-------");
        for (const b of bullets) lines.push(`• ${b}`);
        lines.push("");
    }

    lines.push("TRANSCRIPT");
    lines.push("----------");
    for (const seg of opts.segments) {
        lines.push(`${seg.speaker} (${formatDuration(seg.start)}): ${seg.text}`);
        lines.push("");
    }

    return lines.join("\n").trimEnd() + "\n";
}

export function formatTranscriptAsMd(opts: ExportOpts): string {
    const lines: string[] = [];
    lines.push(`# ${opts.title ?? TITLE_FALLBACK}`);
    lines.push("");
    lines.push(`*Recorded ${formatHeaderDate(opts.createdAt)} — ${formatDuration(opts.duration)}*`);
    lines.push("");

    const bullets = summaryBullets(opts.summary);
    if (bullets.length > 0) {
        lines.push("## Summary");
        lines.push("");
        for (const b of bullets) lines.push(`- ${b}`);
        lines.push("");
    }

    lines.push("## Transcript");
    lines.push("");
    for (const seg of opts.segments) {
        lines.push(`**${seg.speaker}** \`${formatDuration(seg.start)}\``);
        lines.push("");
        lines.push(seg.text);
        lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by Audia*");
    lines.push("");

    return lines.join("\n");
}

/**
 * Builds a filename that's recognizable in the user's Downloads folder
 * without forcing them to open it. Prefers the session title; falls back
 * to a dated stamp if untitled. Strips characters that are illegal on
 * Windows/macOS/Linux filesystems and caps length to avoid OS limits.
 */
export function suggestedFilename(
    title: string | null,
    createdAt: string | Date,
    ext: "txt" | "md"
): string {
    if (title) {
        const safe = title
            .replace(/[\\/:*?"<>|]/g, "")
            .replace(/\s+/g, " ")
            .trim()
            .slice(0, 80);
        if (safe.length > 0) return `${safe}.${ext}`;
    }

    const stamp = toDate(createdAt).toISOString().slice(0, 10);
    return `audia-transcript-${stamp}.${ext}`;
}

export function downloadAsFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
